### ISSUE TITLE
Officially Outdated and Nonfunctional as of Blender 4.0

### ISSUE THREAD

**Issue by DruCart3456** [Haggets/source-armature-toolkit#2]
**Describe the bug**
This isn't a bug report in the true sense, as the toolkit is no longer being updated. Simply putting this here for people to see attached to this, and to express my sadness, as I have been using this addon for the last few years and its been absolutely fantastic, and I don't like using older versions or multiple versions of Blender. I do hope someone else is able to take this up and fix it, or continue its support. I have no coding knowledge at all to do so myself, or I would.

Actual bug itself that lead me to this is the Constraint Symmetry now creating errors, and no longer functioning, or setting up Bone Groups at all.

**Steps to reproduce behavior**
Update Blender to the latest 4.0 version.

**Logs**
Python: Traceback (most recent call last):
  File "C:\Users\druca\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\source-armature-toolkit-main\ops.py", line 107, in execute
    constraint_symmetry(0, satproperties.affected_side)
  File "C:\Users\druca\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\source-armature-toolkit-main\constraint_symmetry.py", line 97, in constraint_symmetry
    utils.arm.get_bones(False)
AttributeError: module 'source-armature-toolkit-main.utils' has no attribute 'arm'

**Details**:
Blender Version: 4.0

Downloaded through...
- [x] Main branch

Release/Addon Version:
1.0.0

**Additional context**
I do hope I'm wrong and this is actually an easy fix within the files. If not, then, oof.

**Comment by Haggets** [comment]
I'll consider fixing it once i have free time.

**Comment by Haggets** [comment]
Fixed.
